<a href="https://colab.research.google.com/github/senorbeast/tf/blob/main/NN_first.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test /255.0

In [ ]:
model = tf.keras.models.Sequential([
                                    tf.keras.layers.Flatten(input_shape=(28, 28)),
                                    tf.keras.layers.Dense(128, activation ='relu'),
                                    tf.keras.layers.Dropout(0.2),
                                    tf.keras.layers.Dense(10)
])

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.65409076,  0.5712385 ,  0.31549093,  0.20573029, -0.527462  ,
        -0.3484701 , -0.22078452,  0.28858602,  0.34968984,  0.30366194]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.15388449, 0.1416487 , 0.10968388, 0.09828208, 0.04721206,
        0.05646615, 0.06415659, 0.10677218, 0.11349983, 0.10839408]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [ ]:
loss_fn(y_train[:1], predictions).numpy()

2.874114

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2932 - accuracy: 0.9134
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1424 - accuracy: 0.9581
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1073 - accuracy: 0.9674
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0864 - accuracy: 0.9730
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0730 - accuracy: 0.9771


In [ ]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0772 - accuracy: 0.9775


[0.07716768234968185, 0.9775000214576721]

In [ ]:
probability_model = tf.keras.Sequential([model,
                                         tf.keras.layers.Softmax()])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.8922472e-08, 7.5940250e-08, 1.3366173e-06, 6.0714818e-05,
        8.9571172e-12, 6.9343024e-08, 1.9710450e-14, 9.9993432e-01,
        9.9429187e-08, 3.3221495e-06],
       [3.0519043e-08, 5.9239417e-05, 9.9991179e-01, 2.8468470e-05,
        1.3060918e-16, 2.3140088e-07, 1.5388382e-08, 6.7844419e-12,
        2.6665083e-07, 1.2871060e-13],
       [4.0547232e-07, 9.9962890e-01, 6.2304040e-05, 2.4008874e-05,
        1.3192174e-05, 3.2748726e-06, 4.9338919e-06, 1.3378297e-04,
        1.2923876e-04, 2.9985873e-08],
       [9.9989593e-01, 1.5259469e-09, 2.7101441e-05, 2.1692683e-08,
        3.6605375e-08, 3.0568083e-06, 6.2387109e-05, 4.6325458e-06,
        4.7467015e-08, 6.7869109e-06],
       [3.0048855e-06, 3.9233612e-08, 4.6451096e-06, 2.4534458e-07,
        9.9747580e-01, 1.4676996e-06, 6.3394673e-06, 2.1094158e-04,
        1.0997594e-06, 2.2964126e-03]], dtype=float32)>